language: python
python:
  - "2.7.14"
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
install:
  - pip install -r requirements.txt -U -r inner_requirements.txt
script:
  - find . -name "*.py" | xargs pylint --reports=n
